// Every word the app shows lives here, so a Swahili version can be added later
// by adding a second object with the same shape. Short, plain words.

export const s = {
  app: {
    name: "Jasiri",
    tagline: "Your work, on record.",
    noConnection: "No connection. We will retry when you are back online.",
    retrying: "Retrying…",
    back: "Back",
    home: "Home",
    save: "Save",
    saved: "Saved",
    cancel: "Cancel",
    close: "Close",
    done: "Done",
    yes: "Yes",
    no: "No",
    loading: "Loading…",
    kes: "KES",
    today: "Today",
    thisWeek: "This week",
    print: "Print",
    downloadExcel: "Excel",
    downloadPdf: "PDF",
    downloadCsv: "CSV",
    search: "Search",
    none: "Nothing here yet.",
    signOut: "Sign out",
    refresh: "Refresh",
    copy: "Copy",
    copied: "Copied",
    tryAgain: "Try again",
  },

  auth: {
    signInTitle: "Sign in",
    signUpTitle: "Create your account",
    phoneOrEmail: "Phone number or email",
    phoneOrEmailHint: "Cashier accounts use an email.",
    pin: "6-digit PIN",
    pinAgain: "PIN again",
    signIn: "Sign in",
    signUp: "Create account",
    noAccount: "New here? Create an account",
    haveAccount: "Have an account? Sign in",
    fullName: "Your name",
    phone: "Phone number",
    useEmail: "Use an email instead (for a shared cashier account)",
    usePhone: "Use a phone number instead",
    email: "Email",
    whatDoYouDo: "What do you do?",
    roleBarber: "Barber",
    roleBarberHint: "Codes, your own client book and booking link.",
    roleService: "Service staff",
    roleServiceHint: "Head wash, massage, facial. You receive codes from barbers.",
    roleCashier: "Cashier",
    roleCashierHint: "Take payment and print the payout sheet.",
    roleManager: "Shop owner or manager",
    roleManagerHint: "Set up the shop, approve staff, see flags and reports.",
    cashierEmailTip: "Shared till phone? Use an email so the account can be handed to the next cashier.",
    rolesNote: "Your shop manager confirms your role when you join a shop.",
    iAmBarber: "I am a barber",
    iAmBarberHint: "You get a client book and your own booking link.",
    handle: "Your booking link name",
    handleHint: "Letters, numbers and dashes. Your link will be",
    forgotPin: "Forgot your PIN? Ask the Jasiri team to reset it.",
    changePin: "Change PIN",
    currentPin: "Current PIN",
    newPin: "New PIN",
    pinChanged: "PIN changed. Other phones were signed out.",
    suspended: "This account is suspended. Contact the Jasiri team.",
    sessionExpired: "Please sign in again.",
  },

  home: {
    hello: "Hello",
    noShop: "You are not in a shop yet.",
    noShopBarber: "Your client book and booking link work without a shop. Codes need a shop.",
    createShop: "Create a shop",
    joinShop: "Join a shop",
    pending: "Waiting for coworkers in this shop to confirm you. Ask them to open Jasiri and tap Yes.",
    switchShop: "Switch shop",
    newCode: "New code",
    myDay: "My day",
    clientBook: "Client book",
    earnings: "My earnings",
    queue: "My queue",
    cashier: "Cashier",
    manage: "Manage shop",
    summary: "Daily summary",
    flags: "Flags",
    usage: "Usage",
    problems: "Problems",
    audit: "Audit log",
    payout: "Payout sheet",
    bookingLink: "Booking link",
    availability: "Bookable times",
    account: "My account",
    admin: "Platform admin",
    guide: "How to use",
    myCuts: "My cuts",
    myServices: "My services",
    newCodeHint: "Tap after every cut",
    queueHint: "Clients sent to you",
    cashierHint: "Take payment",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    trialEnds: "Free month ends",
    payDue: "Your free month is over. Please pay to keep using Jasiri.",
    payInstructions: "How to pay",
    perMonth: "per month",
  },

  shop: {
    createTitle: "Create a shop",
    name: "Shop name",
    area: "Area",
    create: "Create shop",
    joinTitle: "Join a shop",
    joinCode: "Shop join code",
    joinCodeHint: "Ask the shop manager for the 6-letter code.",
    welcomeJoin: "Account created. Now join your shop: ask the shop manager for the join code.",
    welcomeCreate: "Account created. Now set up your shop, then share the join code with your staff.",
    signedUpAs: "Signed up as",
    wantsToJoin: "Wants to join",
    findTitle: "Find your shop",
    findLabel: "Shop name",
    findHint: "Type the name of the shop where you work. If a coworker already added it, it will pop up.",
    staffCount: (n: number) => (n === 1 ? "1 person" : `${n} people`),
    youreIn: "You're in",
    requested: "Requested",
    notListed: (name: string) => `Not listed? Add "${name}"`,
    addShopTitle: "Add your shop",
    addShopHint: "You'll be its manager until the owner joins. You can hand the manager role over any time.",
    askAs: "I work here as",
    roleOwner: "Owner / manager",
    askToJoinShop: "Ask to join",
    askSent: "Request sent. Ask two coworkers in the shop to open Jasiri and tap Yes. Then you're in.",
    askSentOwner: "Request sent. The shop's current manager must approve you as owner/manager.",
    haveCode: "Have a join code instead?",
    skipForNow: "Skip for now",
    welcomeFind: "Account created. Now find your shop. If nobody has added it yet, add it yourself.",
    requestsTitle: "Wants to join your shop",
    yesWorksHere: "Yes, works here",
    notHere: "No",
    managerMustApprove: "Waiting for the shop manager",
    confirmedOf: (yes: number, needed: number) => `${yes} of ${needed} coworkers confirmed`,
    youSaidYes: "You said yes. Waiting for one more coworker.",
    youSaidNo: "You said no.",
    joined: "Approved. They're in.",
    turnedAway: "Turned away.",
    findOrAdd: "Find or add your shop",
    searchFailed: "Shop search isn't working right now, so we can't check if your shop is already here. Please try again later; don't add the shop yet.",
    findShop: "Find shop",
    askToJoin: "Ask to join",
    requestSent: "Request sent. The shop manager must approve you before you can use the shop.",
    manageTitle: "Manage shop",
    joinCodeLabel: "Join code",
    inviteLink: "Invite link",
    newJoinCode: "New join code",
    requests: "Join requests",
    members: "Members",
    approve: "Approve",
    reject: "Reject",
    roles: "Roles",
    setRoles: "Save roles",
    endMembership: "Remove from shop",
    leaveShop: "Leave this shop",
    confirmLeave: "Leave this shop? Your client book and booking link stay with you.",
    confirmEnd: "Remove this person from the shop?",
    onDuty: "On duty today",
    offDuty: "Off duty",
    goOnDuty: "Start my day (on duty)",
    goOffDuty: "Go off duty",
    role: {
      manager: "Shop manager",
      barber: "Barber",
      service_staff: "Service staff",
      cashier: "Cashier",
    } as Record<string, string>,
  },

  code: {
    newTitle: "New code",
    whoIsClient: "Who is the client?",
    returning: "Returning client",
    newClient: "New client",
    noDetails: "No details",
    noDetailsHint: "Counts for pay, but does not go into your client book.",
    searchClients: "Name or last digits",
    handPhone: "Hand the phone to the client.",
    phoneFirst: "Start with your phone number. If you have been here before, we fill in your name.",
    checking: "Checking…",
    servedBefore: (name: string) => `Welcome back, ${name}. You have been served in this shop before.`,
    alreadyMine: "Already in your client book.",
    notInBook: "Not in your book? Tap New client and type his number. If he has been served here before, his name fills in.",
    clientFirstName: "Your first name",
    clientPhone: "Your phone number",
    consent: (barber: string) => `Save my name and number with ${barber} for visits and bookings.`,
    amountCharged: "Amount you charged (KES)",
    makeCode: "Make code",
    showToClient: "Show this to the client",
    confirmMyCode: "Confirm my code",
    clientTaps: "Client taps to confirm",
    cancelCode: "Cancel this code",
    confirmCancel: "Cancel this code? Only possible before the client confirms.",
    sendTo: "Send the client to",
    unassigned: "Nobody is on duty. The code is in the shared list for any service staff.",
    cashierCanSee: "The cashier can see this code now.",
    newAnother: "New code",
    fromBooking: "From booking",
    status: {
      created: "Waiting for client",
      open: "Open",
      paid: "Paid",
      voided: "Voided",
      cancelled: "Cancelled",
    } as Record<string, string>,
    service: {
      pending: "Not yet at service",
      in_progress: "At service",
      done: "Service done",
      no_service: "No service",
      skipped: "Paid before service",
    } as Record<string, string>,
    verification: {
      cashier_confirmed: "Cashier-confirmed",
      self_recorded: "Self-recorded",
      voided: "Voided",
    } as Record<string, string>,
    serviceOnly: "Service only (no barber)",
    noBarber: "No barber",
  },

  queue: {
    title: "My queue",
    mine: "Sent to me",
    unassigned: "Unassigned",
    take: "Take",
    open: "Open",
    clientConfirm: "Client: tap to confirm",
    clientConfirmHint: "Ask the client to tap this when he reaches you.",
    addService: "Add a service",
    amount: "Amount (KES)",
    whatService: "Service (optional, e.g. head wash)",
    add: "Add",
    remove: "Remove",
    done: "Done – send to cashier",
    noService: "No service",
    confirmNoService: "Client leaving without any service?",
    handover: "Hand to a colleague",
    pickColleague: "Pick a colleague",
    serviceOnlyCode: "New service-only code",
    serviceOnlyHint: "For a client who only wants your services, no haircut.",
    firstNameOptional: "Client's first name (optional)",
    notOnDuty: "You are off duty. Codes go to staff who are on duty.",
    empty: "No clients waiting.",
    yourServices: "Your services on this code",
  },

  cashier: {
    title: "Cashier",
    ready: "Open codes",
    paidToday: "Paid today",
    voidedToday: "Voided today",
    find: "Find code",
    barber: "Barber",
    staff: "Service",
    expected: "Total typed by staff",
    amountPaid: "Amount the client paid (KES)",
    sameAsTotal: (n: string) => `Same as total: ${n}`,
    clientTapPaid: (n: string) => `Client: tap to confirm you paid ${n}`,
    paid: "Paid",
    mismatch: "Different from the staff total",
    stillAtService: "Still with service staff. Paying now closes the service.",
    void: "Void",
    voidTitle: "Void this code",
    voidReason: "Reason",
    voidNote: "Note",
    reasons: {
      left_without_paying: "Left without paying",
      mistake: "Mistake",
      duplicate: "Duplicate",
      other: "Other",
    } as Record<string, string>,
    confirmVoid: "Void this code",
  },

  earnings: {
    title: "My earnings",
    verified: "Cashier-confirmed",
    open: "Open (self-recorded)",
    voided: "Voided",
    codes: "codes",
    myCodes: "My codes",
    asBarber: "Cut",
    asService: "Service",
    reportProblem: "Report a problem",
    problemNote: "What is wrong?",
    send: "Send",
    problemSent: "Sent to the shop manager and the Jasiri team.",
    export: "Download my record",
    period: "Period",
    lastWeek: "Last week",
    thisMonth: "This month",
    lastMonth: "Last month",
  },

  clients: {
    title: "Client book",
    add: "Add client",
    due: "Due for a cut",
    visits: "visits",
    lastVisit: "Last visit",
    daysAgo: (n: number) => (n === 0 ? "today" : n === 1 ? "1 day ago" : `${n} days ago`),
    avgGap: (n: number) => `Comes every ${n} days`,
    totalSpent: "Total with you",
    neverVisited: "No paid visit yet",
    export: "Export CSV",
    call: "Call",
    rename: "Change name",
  },

  booking: {
    dayTitle: "My day",
    bookings: "Bookings",
    walkIn: "Open – walk-ins",
    startCode: "Start code",
    noShow: "No-show",
    cancelBooking: "Cancel booking",
    manual: "Add a booking",
    manualHint: "For a client who texted you.",
    time: "Time",
    date: "Date",
    sourceLink: "Booked by link",
    sourceManual: "Added by you",
    status: {
      booked: "Booked",
      cancelled: "Cancelled",
      no_show: "No-show",
      completed: "Code started",
    } as Record<string, string>,
    availabilityTitle: "Bookable times",
    availabilityHint: "Only these times show on your booking link. The rest of your day stays free for walk-ins.",
    slotLength: "Time per booking",
    minutes: "min",
    addRange: "Add hours",
    from: "From",
    to: "To",
    blocks: "Days off and busy times",
    addBlock: "Add",
    offDay: "Off day",
    busy: "Busy",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    shareTitle: "Share your booking link",
    copyLink: "Copy link",
    quickReply: "WhatsApp quick reply",
    quickReplyText: (link: string) => `Niko na client. Chagua time hapa: ${link}`,
    quickReplyHint: "Save this as a WhatsApp Business quick reply.",
    qr: "QR code for your mirror",
    printQr: "Print QR code",
    scanToBook: "Scan to book",
    about: "About you and your prices (shown on your page)",
    // public page
    bookWith: "Book",
    pickTime: "Pick a time",
    noTimes: "No open times this week. Walk in or try again later.",
    yourPhone: "Your phone number",
    next: "Next",
    yourFirstName: "Your first name",
    book: "Book",
    taken: "That time was just taken. Pick another.",
    booked: "You are booked",
    bookedFor: "Booked for",
    keepLink: "Keep this page. Use the link below to cancel.",
    cancelLink: "Cancel my booking",
    cancelled: "Your booking is cancelled.",
    confirmCancelPublic: "Cancel this booking?",
    alreadyBooked: "This number already has a booking with this barber.",
    poweredBy: "Booking by Jasiri",
    notFound: "This booking link does not exist.",
  },

  services: {
    title: "My services & prices",
    hint: "Clients see these when they book. You can still change the amount on any code.",
    hintStaff: "Clients booking a barber in your shop can add these as extras.",
    name: "Service",
    price: "KES",
    minutes: "Min",
    add: "Add a service",
    suggestions: "Quick add",
    save: "Save prices",
    saved: "Saved. Clients see the new prices now.",
    empty: "No services yet. Add what you offer and what it costs.",
    menu: "Services & prices",
    extras: "Extras in this shop",
    from: "from",
    pick: "What do you want?",
    pickHint: "Optional. Prices are a guide; pay at the shop.",
    estimate: "Estimated total",
    tapToAdd: "Tap your services to fill the amount",
    barberSuggest: ["Haircut", "Fade", "Taper", "Beard trim", "Shave", "Kids cut", "Dye", "Line-up"],
    staffSuggest: ["Head wash", "Massage", "Facial", "Scrub", "Steam", "Nails"],
  },

  photos: {
    title: "My cuts",
    hint: "Show off your best work. These photos appear on your booking link.",
    profile: "Profile photo",
    changePhoto: "Change photo",
    addPhoto: "Add photo",
    addCuts: "Add cuts",
    styleName: "Style name (optional, e.g. Taper fade)",
    uploading: "Uploading…",
    remove: "Remove",
    count: (n: number) => `${n} of 12 photos`,
    empty: "No photos yet. Add your best cuts so clients choose you.",
    myWork: "My work",
  },

  manager: {
    summaryTitle: "Daily summary",
    created: "Codes created",
    paid: "Paid",
    voided: "Voided",
    cancelled: "Cancelled",
    open: "Still open",
    till: "Till should hold (cash + M-Pesa)",
    expected: "Staff totals on paid codes",
    barberTotal: "Barbers",
    serviceTotal: "Service staff",
    mismatches: "Paid amount differs from staff total",
    payoutTitle: "Payout sheet",
    person: "Person",
    paidCodes: "Paid codes",
    earned: "Amount",
    openCodes: "Open",
    flagsTitle: "Flags",
    openAfterDay: "Confirmed but unpaid after the day ended",
    mismatchList: "Paid amount differs from staff total",
    voidsByPerson: "Voids per person",
    handovers: "Codes handed between service staff",
    voidRecreate: "Voided and remade under a different barber within 10 minutes",
    openProblems: "Open problem reports",
    usageTitle: "Usage",
    withPhone: "Codes with a client phone (target 80%)",
    reachPaid: "Confirmed codes that reach paid",
    medianMinutes: "Median minutes from confirm to paid",
    bookingSplit: "Bookings by link vs added by barber (target 30% link)",
    noShowRate: "No-show rate",
    activeStaff: "Who used the app",
    problemsTitle: "Problem reports",
    resolve: "Mark resolved",
    resolutionNote: "What was done",
    resolved: "Resolved",
    auditTitle: "Audit log",
    loadMore: "Load more",
    perBarber: "Per barber: paid / confirmed · with phone",
    last7: "Last 7 days",
    last30: "Last 30 days",
  },

  admin: {
    title: "Platform admin",
    users: "Accounts",
    shops: "Shops",
    usage: "Usage",
    settings: "Settings",
    clients: "Client deletion",
    suspend: "Suspend",
    unsuspend: "Unsuspend",
    paidUntil: "Paid until",
    setPaid: "Save",
    resetPin: "Reset PIN",
    newPinFor: "New PIN for this account",
    pinReset: "PIN reset. The person was signed out everywhere.",
    findByPhone: "Client phone number",
    delete: "Delete",
    confirmDelete: "Delete this client record? Past codes stay, without the client.",
    paymentInstructions: "Payment instructions shown to barbers",
    monthlyPrice: "Monthly price (KES)",
    killTitle: "Kill criteria",
    killUsage: "Barbers with 15+ codes in the last 7 days (target 60%)",
    killPay: "Barbers paying after the free month (target 40%)",
    signups: "New sign-ups",
    newShops: "New shops",
    movedWithBook: "Barbers who joined a new shop with an existing client book",
    dailyActive: "People active per day",
  },

  landing: {
    signIn: "Sign in",
    getStarted: "Get started",
    nav: { how: "How it works", features: "Features", pricing: "Pricing", contact: "Contact" },
    eyebrow: "Built for Kenyan barbershops",
    title: "Every cut on record. Every shilling accounted for.",
    sub: "Jasiri gives each client a code from the barber who served him. It follows him to the head wash and the cashier, so nobody can move your count. Plus your own client book and booking link.",
    ctaPrimary: "Create free account",
    ctaSecondary: "See how it works",
    freeNote: "30 days free. No card. Works on any Android phone.",
    mockShop: "Kinyozi Bora",
    mockSendTo: "Send the client to",
    mockStaff: "Mary",
    howTitle: "How it works",
    howSub: "Three taps from chair to cashier.",
    steps: [
      { t: "Barber makes a code", d: "After the cut, the barber types what he charged. The client taps Confirm my code. The barber on that code can never be changed." },
      { t: "Service staff add theirs", d: "The code appears on the head-wash lady's phone. She records her work. If the client skips the wash, nothing is recorded for her." },
      { t: "Cashier confirms payment", d: "The client pays cash or M-Pesa and taps his code on the cashier screen. That tap marks it paid. Everyone's earnings update." },
    ],
    featuresTitle: "Made for everyone in the shop",
    features: [
      { icon: "scissors", t: "Barbers", d: "Proof of every client you serve. Download your record as Excel or PDF and settle pay without arguments." },
      { icon: "book", t: "Your own client book", d: "Names, visits and who is due for a cut. It belongs to you, and moves with you if you change shops." },
      { icon: "link", t: "Your booking link", d: "Clients pick a time from your link. Share it on WhatsApp or print the QR code for your mirror." },
      { icon: "sparkles", t: "Service staff", d: "Codes arrive on your phone. Record each wash, massage or facial. Your earnings list is your evidence." },
      { icon: "cash", t: "Cashiers", d: "See what each client owes, confirm payment in a tap, and print the daily payout sheet." },
      { icon: "shield", t: "Shop managers", d: "Flags for unpaid codes, voids and mismatches. An audit log nobody can edit." },
    ],
    showcaseTitle: "Your work, your link",
    showcaseSub: "Add photos of your best cuts. Clients see them on your booking page and book you directly.",
    showcasePoints: ["Profile photo and up to 12 cuts", "Bookable times you control", "No app for clients to install"],
    pricingTitle: "Simple pricing",
    pricingFree: "First 30 days",
    pricingFreeValue: "Free",
    pricingAfter: "Then, per barber",
    perMonth: "/ month",
    pricingStaff: "Service staff, cashiers and shop managers use Jasiri free.",
    pricingNoMoney: "Jasiri never touches your money. Clients pay the cashier as usual.",
    faqTitle: "Questions",
    faq: [
      { q: "Do clients need to install anything?", a: "No. Clients tap on the staff phones and book through your link in any browser." },
      { q: "Can the shop see my clients' phone numbers?", a: "No. Your client book is yours. The shop only ever sees a client's first name." },
      { q: "What if the internet goes off?", a: "Jasiri shows a banner and finishes the tap when the connection returns. It never records anything twice." },
      { q: "Does it handle payments?", a: "No. Clients pay cash or M-Pesa as usual. Jasiri only records who did the work and what was paid." },
    ],
    contactTitle: "Talk to us",
    contactSub: "Want Jasiri in your shop? Reach out and we will set you up.",
    email: "Email",
    phone: "Call",
    whatsapp: "WhatsApp",
    instagram: "Instagram",
    location: "Based in",
    placeholderNote: "Contact details coming soon.",
    footer: "Jasiri. Every cut on record.",
  },

  errors: {
    generic: "Something went wrong. Try again.",
    invalid_phone: "Use a Kenyan number like 0712 345 678.",
    invalid_email: "Check the email address.",
    pin_format: "The PIN must be 6 digits.",
    pin_mismatch: "The two PINs are different.",
    wrong_pin: "Wrong phone/email or PIN.",
    locked: (min: number) => `Too many wrong PINs. Try again in ${min} minutes.`,
    rate_limited: "Too many tries. Wait a little and try again.",
    phone_taken: "That phone number already has an account. Sign in instead.",
    email_taken: "That email already has an account.",
    handle_taken: "That link name is taken. Try another.",
    handle_format: "Use 3–30 letters, numbers or dashes.",
    name_required: "Enter a name.",
    not_signed_in: "Please sign in again.",
    account_suspended: "This account is suspended.",
    not_allowed: "You can't do that here.",
    shop_not_found: "No shop with that code.",
    already_member: "You are already in this shop or waiting for approval.",
    last_manager: "The shop needs at least one shop manager. Give someone else the role first.",
    pick_a_role: "Pick at least one role.",
    amount_required: "Enter the amount.",
    consent_required: "The client must tick the box to save his details.",
    client_not_found: "Client not found.",
    booking_not_found: "Booking not found.",
    already_confirmed: "The client already confirmed this code.",
    code_not_found: "Code not found.",
    code_not_open: "This code is not open.",
    code_is_final: "This code is paid or voided. It can't change.",
    already_paid: "This code is already paid.",
    already_assigned: "Someone already took this code.",
    not_your_code: "This code is with someone else now.",
    service_closed: "The service on this code is finished.",
    add_a_service_first: "Add a service first, or tap No service.",
    remove_services_first: "Remove the services first.",
    not_service_staff: "That person is not service staff here.",
    pick_someone_else: "Pick someone else.",
    reason_required: "Pick a reason.",
    note_required: "Add a short note.",
    slot_taken: "That time was just taken. Pick another.",
    slot_in_past: "That time has passed. Pick another.",
    slot_not_bookable: "That time is no longer open. Pick another.",
    already_booked: "This number already has a booking with this barber.",
    too_far_ahead: "Pick a time within the next 60 days.",
    barber_not_found: "This booking link does not exist.",
    bad_transition: "That change is not possible now.",
    not_open: "Already handled.",
    not_pending: "Already handled.",
    not_active: "This membership has ended.",
    manager_must_approve: "Only the shop manager can approve an owner or manager.",
    barber_profile_required: "Turn on \"I am a barber\" in My account first.",
    requests_failed: "Couldn't load join requests. Check your connection; if it keeps happening, tell the Jasiri team.",
    service_not_found: "One of those services is no longer offered. Pick again.",
    too_many_services: "Too many services. Keep it to the main ones.",
    too_many_photos: "You can have up to 12 photos. Remove one first.",
    upload_failed: "Upload failed. Check your connection and try again.",
  } as Record<string, string | ((n: number) => string)>,
};

export function errorText(code: string | undefined | null): string {
  const v = code ? s.errors[code] : undefined;
  return typeof v === "string" ? v : s.errors.generic as string;
}
